
oauth_config:
  application_id: "4d2b474e-7b70-4b7e-aff5-7313567c2c38"               # Add your Application ID provided when you created an app in the PDN.
  application_name:  "HelloWorld"  # The Application Name can be arbitrary, you needn't change it from HelloWorld
  client_string: "gbtestc"         # For Sandbox Campus, leave clientString as gbtestc.
  consumer_key: "4d2b474e-7b70-4b7e-aff5-7313567c2c38"                 # For the consumerKey property, set this to the Token Key Moniker provided when you created an app.
  consumer_secret: "DmyLEZn8ts7MuOUm"              # For the consumerSecret property, set this to the Shared Secret provided when you created an app.

oauth2_handler:
  assertion:
    username: "anisha.srivastava123.student@gmail.com"                   # Enter a user's username here, provided when you created an app.
                                   #  We recommend working with a teacher account, but using a student can demonstrate different permissions.
